#!/bin/sh

if which realpath > /dev/null; then
  echo "This script requires the \"realpath\" command to function."
  echo "Aborting backup repository creation."
  exit 1
fi

REPO_PATH="$(dirname $(realpath $0))"
if [ -z "$1" ]; then
  echo "No path specified!"
  echo "Usage: $0 /path/to/new/repo"
  exit 1
fi
mkdir -pv $1
if [ -e $1 ]; then
  touch $1/backup-filter $1/backup-log
  cp $REPO_PATH/example-server-config $1/backup-config
  ln -s $REPO_PATH/backup-server-script.sh $1/backup-script
fi
echo "Backup repository created at \"$1\"."