#!/bin/sh

use_colors() {
    RC="\033[0;31m" # red color
    GC="\033[0;32m" # green color
    YC="\033[0;33m" # yellow color
    CC="\033[0;36m" # cyan color
    NC="\033[0m"    # no color
}
[ "$SHELL" != "/bin/csh" ] && use_colors

get_suite_path() {
    # ($1: name of command, i.e. "$0")
    SUITE_PATH="$(dirname $1)"
    if [ "$SUITE_PATH" != "." ]; then
        SUITE_PATH="$PWD/$SUITE_PATH"
    else
        SUITE_PATH="$PWD"
    fi
}

get_suite_path $0

if [ -e $HOME/.backup-suite ]; then
    if [ ! $HOME/.backup-suite -ef $SUITE_PATH ]; then
        echo $YC"Backup suite already present in home directory,"$NC
        echo $RC"but pointing to something else."$NC
        echo $YC"Manually resolve this issue and try again."$NC
        echo $RC"Aborting \"backup-menu\" installation."$NC
        exit 1
    else
        echo $CC"Backup suite already present in home directory."$NC
    fi
else
    ln -sv $SUITE_PATH $HOME/.backup-suite
    echo $YC"Backup suite linked to home directory."$NC
fi

echo $GC"Done.\n"$NC
