#!/bin/sh
#
# hostname of client to back up data from
# (as configured in ssh config file)
BACKUP_CLIENT_HOSTNAME=""
# root path of backed up data on client system
# (used by rsync, so make sure to end with a "/"!)
BACKUP_CLIENT_PATH=""
# path at which to store backed up data inside the repository
# (leave empty to put backed up data at the repository root,
# otherwise make sure to end with a "/"!)
BACKUP_DEST_FOLDER=""